name: Build Docker image

on:
  push:
    branches:
      - main

jobs:
  tag_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t imparty:latest .
          docker tag imparty:latest colour93/imparty:latest

      - name: Push Docker image
        run: docker push colour93/imparty:latest
