name: cd

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    environment: CD
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CD_SSH_HOST }}
          username: ${{ secrets.CD_SSH_USER }}
          key: ${{ secrets.CD_SSH_KEY }}
          script: |
            docker container stop imparty
            docker container rm imparty
            docker pull colour93/imparty:latest
            docker run -p 24932:24932 -v ${{ vars.IMPARTY_DATA_PATH }}:/usr/src/app/data --name="imparty" -d --restart=on-failure:3 --network host -e IMPARTY_FRONT_URL=${{ vars.IMPARTY_FRONT_URL }} -e TZ=Asia/Shanghai colour93/imparty:latest
